language: python
python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest test/ -v

notifications:
  email:
    recipients:
      - chaudhary.kc.kunal@gmail.com
    on_success: never
    on_failure: always