logs:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - [%(name)s] [%(levelname)s] - %(message)s'
      datefmt: '%d%b%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: simple
      filename: logs/app.log
      mode: a
  loggers:
    __main__:
      level: DEBUG
      handlers: [console, file]
      propagate: no
  root:
    level: INFO
    handlers: [file]

webdriver:
  wait:
    time: 10 #seconds

instagram:
  loginUrl: https://www.instagram.com/accounts/login/
  handleBaseUrl: https://www.instagram.com/
  scrollsWithoutNewUsersLimit: 5 #numbers of scrolls without new users
  sleepTimeAfterScroll: 2 #seconds
  regexToGetIdFromHtmlSource: \"has_requested_viewer\":(.)*\"id\":(.)*\"is_business_account\":.
  api:
    url: https://www.instagram.com/graphql/query/
    query_hash: # TODO: scrap query_hash from javascript
      followers: 56066f031e6239f35a904ac20c9f37d9
      followings: c56ee0ae1f89cdbd1c89e2bc6b8f3d18
    include_reel: false
    fetch_mutual: false
    first: 50
    sleepTimeAfterQuery: 2 #seconds
    limit: 200 #queries per hour in a session
